export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const ADD_VISITED_VIEWS = 'ADD_VISITED_VIEWS'
export const DEL_VISITED_VIEWS = 'DEL_VISITED_VIEWS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
